# Generated by Django 3.2.8 on 2021-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rename_portfolio_securities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(auto_now=True, verbose_name='Last update')),
                ('eur_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='EUR rate')),
                ('rub_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='RUB rate')),
            ],
        ),
        migrations.AlterModelOptions(
            name='securities',
            options={'ordering': ['ticker']},
        ),
    ]
