# Generated by Django 3.2.8 on 2021-10-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0005_auto_20211016_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Portfolio name')),
                ('graph', models.ImageField(upload_to='portfolio_graph', verbose_name='Portfolio pie graph')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='securities',
            name='quantity',
        ),
        migrations.AddField(
            model_name='securities',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='sector',
            field=models.CharField(choices=[('BMAT', 'Basic Materials'), ('BOND', 'Bonds'), ('CASH', 'Cash'), ('COM', 'Communication Services'), ('CYCL', 'Consumer Cyclical'), ('DEF', 'Consumer Defensive'), ('ENER', 'Energy'), ('ETF', 'ETF'), ('FIN', 'Financial Services'), ('GOLD', 'Gold'), ('HEAL', 'Healthcare'), ('IND', 'Industrials'), ('EST', 'Real Estate'), ('TECH', 'Technology'), ('UTIL', 'Utilities')], max_length=20, verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.securities')),
            ],
        ),
    ]
