# Generated by Django 3.2.8 on 2021-10-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20211020_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PieGraph',
        ),
    ]
