# Generated by Django 3.2.8 on 2021-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_portfolio_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker'),
        ),
    ]
