# Generated by Django 3.2.8 on 2021-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_rename_securities_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.CharField(max_length=16, unique=True, verbose_name='Ticker'),
        ),
    ]
