# Generated by Django 3.2.8 on 2021-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_auto_20211103_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='last_update_date',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='update_date',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='security',
            name='not_found_on_market',
            field=models.BooleanField(default=False, verbose_name='Is not found on market?'),
        ),
    ]
