# Generated by Django 3.2.8 on 2021-11-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20211106_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='security',
            name='sector',
            field=models.CharField(blank=True, choices=[('BMAT', 'Basic Materials'), ('BOND', 'Bonds'), ('CASH', 'Cash'), ('COM', 'Communication Services'), ('CYCL', 'Consumer Cyclical'), ('DEF', 'Consumer Defensive'), ('ENER', 'Energy'), ('ETF', 'ETF'), ('FIN', 'Financial Services'), ('GOLD', 'Gold'), ('HEAL', 'Healthcare'), ('IND', 'Industrials'), ('EST', 'Real Estate'), ('TECH', 'Technology'), ('UTIL', 'Utilities')], max_length=20, null=True, verbose_name='Sector'),
        ),
    ]
