# Generated by Django 3.2.8 on 2021-11-07 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20211106_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='figi',
            field=models.CharField(max_length=12, unique=True, verbose_name='FIGI'),
            preserve_default=False,
        ),
    ]
