# Generated by Django 3.2.8 on 2021-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_security_figi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='graph',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='country_graph',
            field=models.ImageField(null=True, upload_to='portfolio_graph', verbose_name='Country pie graph'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currency_graph',
            field=models.ImageField(null=True, upload_to='portfolio_graph', verbose_name='Currency pie graph'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sector_graph',
            field=models.ImageField(null=True, upload_to='portfolio_graph', verbose_name='Sector pie graph'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='securities_graph',
            field=models.ImageField(null=True, upload_to='portfolio_graph', verbose_name='Securities pie graph'),
        ),
    ]
