# Generated by Django 3.2.8 on 2021-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_auto_20211108_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='market_graph',
            field=models.ImageField(null=True, upload_to='portfolio_graph', verbose_name='Market pie graph'),
        ),
    ]
